### PR TITLE
Roman Numeral Converter

### PR DESCRIPTION
**Pull request by faridafaqiri**
## Overview
This pull request adds a complete Roman Numeral Converter web application. The application allows users to enter a number between 1 and 3999 and convert it to its corresponding Roman numeral. The project includes HTML, CSS, and JavaScript files, along with a responsive design for improved usability on various devices.

## Files Added
1- index.html: Contains the structure of the web application, including an input field, a button, and an output area.
2- script.js: Implements the logic for input validation and conversion of numbers to Roman numerals.
3- styles.css: Provides styling for the application, including layout, typography, and responsive design.

## How to Test
1- Clone the repository to your local machine.
    git clone git@github.com:faridafaqiri/roman-numeral-converter.git
2-Navigate to the project directory.
   cd roman-numeral-converter
3- Open index.html in your web browser.
4- Enter a number between 1 and 3999 in the input field.
5- Click the "Convert to Roman Numeral" button.
6- Verify that the correct Roman numeral is displayed.
7- Test with various inputs, including invalid numbers (e.g., non-numeric values, numbers less than 1 or greater than 3999) to ensure proper error handling.

### CODE REVIEW

**Comment by faridafaqiri** [comment]
@Khatira Fikrat
hello khatira jan this is my second project using JavaScript please give me feedback.

**Comment by faridafaqiri** [comment]
@Fikrat2002
dear khaitra please give me feedback.

**Comment by Fikrat2002** [comment]
Hi @far_faqiri 🙋‍♀,

Great job! 💯 You've nailed all the project requirements👏Your feature is complete! Congratulations!!! 🎊🏆

Status: Approved ✅
Note: A tiny change is required📍
Everything looks perfect. Just  add a deployment link in your README file then merge your project 🏆🎊👏

Highlights 🌞
🏆 Successfully implemented a great design
✅ Created a professional repository with your project name
✅ Passed FreeCodeCamp requirements for the project 
✅ Used Gitflow correctly by creating a development branch, setting it as default, and making commits on your feature branch
✅ Wrote meaningful commit messages
✅ Set up appropriate linter configurations based on your project's language
✅ No linter errors!
✅ Followed the task and used command-line commits
✅ Submitted a pull request from your feature branch to the development branch and shared the link for review
✅ Provided a clear and detailed description of your work in the PR
✅ Maintained clean code
✅ Created a professional README.md file in your repository
✅ The project is responsive 
❌ Created live deployment link

**Comment by faridafaqiri** [comment]
@Fikrat2002 
thanks for your feedback I will added deployment link in Readme file.

**Comment by faridafaqiri** [comment]
@ahzamir 
I'm waiting for your review and feedback

**Review by ahzamir — APPROVED** [review]
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
